volume=70
volume-max=200 
geometry=12%
ontop=yes
osc=no

no-input-default-bindings
sub-font="cozettevector"
sub-font-size=36
sub-color="#FFc9fff5"
sub-border-color="FF000000"
sub-spacing=0.3
alang=ger,en,eng
slang=ger,eng
image-display-duration=inf

term-status-msg="\nAV: ${time-pos} / ${duration}"

[extension.mp4]
loop-file=yes

[extension.webm]
loop-file=yes

[extension.gifv]
loop-file=yes

[extension.gif]
loop-file=yes
