let g:minimap_width = 15
let g:minimap_auto_start = 1
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
colorscheme flowershop

packloadall
" ap/vim-css-color                view css colors
" dense-analysis/ale              preview syntax errors
" tpope/vim-sensible              improve defaults
" tpope/vim-endwise               automated statements
" tpope/vim-surround              automated brackets
" rstacruz/vim-closer             closes brackets
" mg979/vim-visual-multi          multiple cursors
" wfxr/minimap.vim                minimap view

nnoremap vap v2ap
nnoremap no :noh<cr>
nnoremap qt *<cr>
nnoremap qr :mark o<bar>:echo printf('*calls kukouoh')<cr>
noremap qf 'o
noremap qq $
noremap w 0
noremap qw `.<cr>
noremap s <C-G> j
noremap join <C-G> J
nnoremap <C-D> 85<up>
nnoremap <C-B> 85<cr>
nnoremap <C-A> gT
nnoremap <C-Z> gt
nnoremap <C-S> :w<cr>
nnoremap <C-C> :qa<cr>

noremap ; :
map q <Nop>
cabbrev ma Texplore<cr>
cabbrev mm source ~/.vim/vimrc <cr>
cabbrev mw w !wl-copy<cr>
cabbrev ms mksession! ~/book/session.vim<cr>
cabbrev mr source ~/book/session.vim<cr>
cabbrev md r!date +\%c<cr>
cabbrev mz !stty size

nnoremap <F3> :NnnPicker<cr>
let g:nnn#command = 'nnn -C'
let g:netrw_home = $HOME"/.vim"
let g:netrw_banner       = 0
let g:netrw_keepdir      = 0
let g:netrw_liststyle    = 1 " or 3
let g:netrw_sort_options = 'i'

set encoding=utf8                 " change output encoding
set fileformats=unix,dos,mac      " unix > dos > mac priority
set backspace=indent,eol,start    " backspace behavior fix
set mouse-=a                      " disable mouse
set modelines=0                   " security (1)
set nomodeline                    " security (2)
set nocompatible                  " drop vi compatibility
set number                        " line number
set smartcase                     " lowercase string priority
set hlsearch                      " show all possible match
set incsearch                     " show match
set lbr                           " text wrap (1)
set wrap                          " text wrap (2)
set breakindent                   " text wrap (3)
set list                          " reveal illegal spaces
set listchars=tab:>-,trail:~,extends:>,precedes:<
set display=lastline              " stop showing me this @@@@
set scrolloff=12                  " equip torch
set sidescrolloff=5               " place lantern
set synmaxcol=150                 " performance (1)
set undolevels=800                " performance (2)
set undoreload=800                " performance (3)
set nottyfast                     " performance (4)
set lazyredraw                    " restrict redraw

set undofile
set backup
set writebackup
set noswapfile
set undodir=~/.vim/tmp/
set backupdir=~/.vim/tmp/bak/
set viminfo+=n~/.vim/viminfo

" trim trailing whitespace
let &fcs='eob: '

" remove newlines & reset cursor position
au bufwritepre * let currPos = getpos(".")
au bufwritepre * %s/\s\+$//e
au bufwritepre * %s/\n\+\%$//e
au bufwritepre *.[ch] %s/\%$/\r/e
au bufwritepre * cal cursor(currPos[1], currPos[2])

" on save conditions
cnoremap w!! execute 'write !doas tee % >/dev/null'
au bufwritepost .Xresources,xresources !xrdb %
au bufwritepre [:;]* throw 'Forbidden file name: ' . expand('<afile>')
au bufwritepre * let &bex = '-' . strftime("%F-%H") . '.bak'
