let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
colorscheme flowershopli

packloadall
" tpope/vim-sensible              improve defaults
" ap/vim-css-color                view css colors
" airblade/vim-gitgutter          view git diff
" mg979/vim-visual-multi          multiple cursors
" vim-skk/eskk.vim                skk japanese text input

nn vap v2ap
nn no :noh<cr>
nn qt *<cr>
nn qr :mark o<bar>:echo printf('*calls kukouoh')<cr>
no qe 'o
no qq $
no w 0
no qw `.<cr>
no s <C-G> j
no <C-G> J
nn <C-D> 85<up>
nn <C-B> 85<cr>
nn <C-A> :bn<cr>
nn <C-Z> :bp<cr>
nn <C-S> :w<cr>
nn <C-C> :qa<cr>

no ; :
map q <Nop>
ca mm source ~/.vim/vimrc <cr>
ca mw w !xclip -sel c<cr>
ca ms mksession! ~/book/session.vim<cr>
ca ma source ~/book/session.vim<cr>
ca md r!date +\%c<cr>
ca mz !stty size

set encoding=utf8                 " change output encoding
set fileformats=unix,dos,mac      " unix > dos > mac priority
set backspace=indent,eol,start    " backspace behavior fix
set mouse-=a                      " disable mouse
set modelines=0                   " security (1)
set nomodeline                    " security (2)
set nocompatible                  " drop vi compatibility
set number                        " line number
set smartcase                     " lowercase string priority
set hlsearch                      " show all possible match
set incsearch                     " show match
set lbr                           " text wrap (1)
set wrap                          " text wrap (2)
set breakindent                   " text wrap (3)
set display=lastline              " stop showing me this @@@@
set scrolloff=12                  " equip torch
set sidescrolloff=5               " place lantern
set synmaxcol=150                 " performance (1)
set undolevels=800                " performance (2)
set undoreload=800                " performance (3)
set nottyfast                     " performance (4)
set lazyredraw                    " restrict redraw

set undofile
set backup
set writebackup
set noswapfile
set undodir=~/.vim/tmp/undo/
set backupdir=~/.vim/tmp/bak/
set viminfo+=n~/.vim/viminfo

set list
set listchars=tab:>-,trail:~,extends:>,precedes:<

" trim trailing whitespace
let &fcs='eob: '

" remove newlines & reset cursor position
au bufwritepre * let currPos = getpos(".")
au bufwritepre * %s/\s\+$//e
au bufwritepre * %s/\n\+\%$//e
au bufwritepre *.[ch] %s/\%$/\r/e
au bufwritepre * cal cursor(currPos[1], currPos[2])

" on save conditions
ca w!! w !ssu -- tee % >/dev/null<cr>
au bufwritepost .Xresources,xresources !xrdb %
au bufwritepost ~/.config/yambar/config.yml !sh -c killall yambar; yambar &

au bufwritepre [:;]* throw 'Forbidden file name: ' . expand('<afile>')
au bufwritepre * let &bex = '-' . strftime("%F-%H") . '.bak'

let g:eskk#directory = {
    \  'path': '"~/.config/eskk"',
    \}

let g:eskk#dictionary = {
    \  'path': '"~/.config/eskk/SKK-JISYO.L"',
    \  'sorted': '1',
    \  'encoding': 'utf-8',
    \}

let g:eskk#large_dictionary = {
    \  'path': '"~/.config/eskk/SKK-JISYO.L"',
    \  'sorted': '1',
    \  'encoding': 'euc-jp',
    \}

let g:eskk#kakutei_when_unique_candidate = 1
let g:eskk#enable_completion = 0
let g:eskk#no_default_mappings = 1
let g:eskk#keep_state = 0
let g:eskk#egg_like_newline = 1

ino <C-K> <C-O>:set keymap:kana<cr>
ino <C-I> <C-O>:set keymap:<cr>
nn <silent> <F3> :call LineNr()<cr>
nn <silent> <F4> :call Paste()<cr>

function! LineNr()
    if g:lines
        :set number
        :echo printf('[*] number')
        let g:lines = 0
    else
        :set nonumber
        :echo printf('[x] number')
        let g:lines = 1
    endif
endfunction

function! Paste()
    if g:lines
        :set paste!
        :echo printf('[x] paste')
        let g:lines = 0
    else
        :set paste
        :echo printf('[*] paste')
        let g:lines = 1
    endif
endfunction

let g:lines = 0
let g:goyo_width = 75
let g:goyo_height = 50

"au vimresized * if exists('#goyo') | exe "normal \<c-w>=" | endif
"au vimenter * :Goyo
"au vimleave * :Goyo!

let g:minimap_width = 15
let g:minimap_auto_start = 1
let g:minimap_auto_start_win_enter = 1

set showtabline=0
au bufread,bufnewfile * set ruler
