font=Cherry:size=9:weight=bold, Symbols Nerd Font:size=12:weight=regular, KH Dot Hibiya 24:weight=bold:size=7, Binggrae:size=7:weight=bold, Siji:weight=regular:size=7
pad=24x24
initial-window-size-pixels=392x250

[scrollback]
lines=50

[tweak]
box-drawing-base-thickness=0.10
scaling-filter=bilinear
sixel=yes

[cursor]
blink=yes
color=f2e2c9 877455

[colors]
foreground=897658
background=f2e2c9

selection-foreground=f2e2c9
selection-background=897658

## FLOWERSHOP LIGHT

regular0=897658
bright0=b29c79

regular1=bf9e78
bright1=d6bd9e

regular2=638e6b
bright2=83af83

regular3=d37575
bright3=e5afa7

regular4=b3c6c9
bright4=c6d1b5

regular5=dbabc3
bright5=efd09b

regular6=b28a67
bright6=e0c89a

regular7=ccb99b
bright7=e0d4be
