# Audio Settings
volume=50
volume-max=200
ao=alsa
alsa-resample=yes
audio-device=alsa/plug:dmix

# Hardware Settings
vo=gpu
video-sync=audio
interpolation=no
deband=no
hwdec=no
hdr-compute-peak=no

# Player Settngs
alpha=no
background='#f2e2c9'
video-margin-ratio-left=0.04
video-margin-ratio-right=0.04
video-margin-ratio-top=0.04
video-margin-ratio-bottom=0.04

# Caption Settings
sub-color='#edcd7d'
sub-font='Undefined-Medium'
sub-font-size=50
sub-spacing=0.3
sub-pos=90
slang=nl,jp,jpn,en,eng
alang=nl,jp,jpn.en,eng

[main]
profile-desc='Runtime Behavior'
profile-cond=not fullscreen
no-input-default-bindings
no-window-dragging
no-scaler-resizes-only
no-hidpi-window-scale
geometry=20%
ontop=yes
osc=no
osd-level=0
loop-file=yes
vo-image-format=png
vf=format=colorlevels=full:colormatrix=auto
term-status-msg="[${time-pos} / ${duration}]"
# Previous Commands:
#    term-status-msg="${?pause==yes:(Paused)}${time-pos} / ${duration}"
#    term-osd-bar-chars=⬬⬬⬬
#    term-osd-bar-chars=▯▯▮▮▯▯
#    alsa-ignore-chmap

# Scripts Directory: "$HOME/.config/mpv/scripts"
# quack.lua
# autocrop.lua
# audio-balance.lua

# Third Party Configuration
user-agent = "Mozilla/5.0"
script-opts=ytdl_hook-ytdl_path=/usr/bin/yt-dlp

[360p]
ytdl-format=bestvideo[height<=360][vcodec=vp9]+bestaudio/bestvideo[height<=360]+bestaudio/best[height<=360]/best
demuxer-max-bytes=1024KiB
