#!/usr/bin/env bash
#
# Dependencies: (xbps)
#    hsetroot xsetroot  * wallpaper tools
#    xwininfo           * determine geometry of open terminal window

hc() {
    herbstclient "$@"
}

hc emit_hook reload

Alt=Mod1
Mod=Mod4

hc mouseunbind --all
hc keyunbind --all

hc mousebind $Mod-Button1  move
hc mousebind $Mod-Button2  zoom
hc mousebind $Mod-Button3  resize

hc keybind $Mod-f          set_attr clients.focus.floating toggle
hc keybind $Mod-q          set_attr clients.focus.floating_geometry 434x286+741+392
hc keybind $Mod-w          set_attr clients.focus.floating_geometry 480x420+250+250
hc keybind $Mod-e          set_attr clients.focus.floating_geometry 626x730+250+250
hc keybind $Mod-r          set_attr clients.focus.floating_geometry 380x420+1100+280
hc keybind $Mod-t          set_attr clients.focus.floating_geometry 380x180+1180+780

hc keybind $Mod-m          set_attr clients.focus.minimized true
hc keybind $Mod-Shift-m    jumpto last-minimized

hc keybind $Mod-Left       focus left
hc keybind $Mod-Down       focus down
hc keybind $Mod-Up         focus up
hc keybind $Mod-Right      focus right

hc keybind $Mod-Shift-q    quit
hc keybind $Mod-Shift-c    reload
hc keybind $Mod-c          close
hc keybind $Mod-a          fullscreen toggle
hc keybind $Mod-z          spawn alacritty -e bash --rcfile $ENV
hc keybind $Mod-n          spawn firefox
hc keybind $Mod-Shift-n    spawn steam
hc keybind $Mod-s          spawn shotgun

tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if [ -n "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

hc keybind $Mod-period  use_index +1 --skip-visible
hc keybind $Mod-comma   use_index -1 --skip-visible

hc keybind $Mod-Tab  cycle
hc keybind $Mod-i    jumpto urgent

# Rules
hc unrule -F
hc rule index=e

hc set focus_follows_mouse  1
hc set focus_stealing_prevention = true

hc rule focus=on
hc rule floatplacement=center
hc rule fixedsize floating=on

hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc rule class~'(.*[Aa]lacritty.*|.*[Uu]rxvt)' floating=on
hc rule class~'(.*[Mm]pv.*|.*[Nn]sxiv)' floating=on
hc rule class~'(.*[Ff]irefox.*|.*[Ss]team)' floating=on

hc rule class=Firefox tag=1

# Themes
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1

hc set frame_bg_normal_color '#897658'
hc set frame_bg_active_color '#897658'

hc attr theme.color '#ebdccd'
# #f9d2cc
# #f3def7
# #dae5c9
# #efdbb8
#hc attr theme.active.color
hc attr theme.urgent.color '#fff1db'

hc attr theme.border_width 14
hc attr theme.inner_width 2
hc attr theme.inner_color '#776358'
hc attr theme.outer_color '#776358'
hc attr theme.outer_width 2
hc attr theme.padding_bottom 0

hc set window_gap 50
hc set frame_padding 0
hc set smart_window_surroundings off
hc set smart_frame_surroundings on
hc set mouse_recenter_gap 0

xsetroot -solid \#b5a192
#xsetroot -bitmap /home/mako/Downloads/30.xbm -bg \#ebd6d2 -fg \#cec2ab
