f1 no-osd af toggle superequalizer=2b=3:3b=1:4b=2

RIGHT seek  5
LEFT  seek -5
space no-osd cycle pause
p no-osd cycle pause
m no-osd cycle mute
0 no-osd add volume 2
9 no-osd add volume -2
q quit

v no-osd cycle sub-visibility 
a no-osd playlist-next
