## BASS BOOST
f1 af toggle superequalizer=2b=3:3b=1:4b=2

## KARAOKE LEVEL / CURE REPETITIVE PLAY
f2 af toggle asetrate=44100*1.08
f3 af toggle asetrate=44100*1.12
f4 af toggle asetrate=44100*1.22
f5 af toggle asetrate=44100*1.42

RIGHT        seek  5
LEFT         seek -5
space        cycle pause
m            cycle mute
0            add volume 2
9            add volume -2
q            quit
h            cycle sub
H            cycle sub down
v            cycle sub-visibility

## DIRECTORY SLIDE
a            playlist-next
z            playlist-prev

## VIDEO SCALING
=            add video-zoom 0.1
-            add video-zoom -0.1
Alt+left     add video-pan-x  0.1
Alt+right    add video-pan-x -0.1
Alt+up       add video-pan-y  0.1
Alt+down     add video-pan-y -0.1
r            set video-zoom 0 ; set video-pan-x 0 ; set video-pan-y 0
e            cycle_values video-rotate 90 180 270 0
