# Audio Settings
ao=alsa
alsa-resample=yes
softvol=yes
volume=50
volume-max=200

# Hardware Settings
vo=gpu
deband=no
hwdec=no
hdr-compute-peak=no

# Software Behavior
no-input-default-bindings
no-scaler-resizes-only
no-hidpi-window-scale
no-window-dragging
ontop=yes
osc=no
osd-level=0
term-status-msg="[${time-pos} / ${duration}]"
# Previous Commands:
#    term-status-msg="${?pause==yes:(Paused)}${time-pos} / ${duration}"
#    term-osd-bar-chars=⬬⬬⬬
#    term-osd-bar-chars=▯▯▮▮▯▯

# Player Settngs
alpha=no
background="#f2e2c9"
geometry=20%
video-margin-ratio-left=0.04
video-margin-ratio-right=0.04
video-margin-ratio-top=0.04
video-margin-ratio-bottom=0.04

# Caption Settings
sub-color="#edcd7d"
sub-font="CozetteVector"
sub-font-size=40
sub-spacing=0.3
sub-pos=90
slang=nl,jp,jpn,en
alang = nl,jp,jpn.en

# Third Party
user-agent = "Mozilla/5.0"
script-opts=ytdl_hook-ytdl_path=/usr/bin/yt-dlp

[extension.jpg]
loop-file=yes

[extension.jpeg]
loop-file=yes

[extension.png]
loop-file=yes

[extension.gif]
loop-file=yes

[extension.gifv]
loop-file=yes

[extension.webp]
loop-file=yes

[extension.webm]
loop-file=yes

[extension.mp4]
loop-file=yes

[extension.mkv]
loop-file=yes

[main]
profile-desc=
profile-cond=width >= 1
vf=format=colorlevels=full:colormatrix=auto
# Previous Commands:
#    image-display-duration=inf
#    vo-image-format=png
#    vf=format=colorlevels=full:colormatrix=rgb
#    hue=25

[360p]
ytdl-format=bestvideo[height<=360][vcodec=vp9]+bestaudio/bestvideo[height<=360]+bestaudio/best[height<=360]/best
demuxer-max-bytes=1024KiB
