## AUDIO SETTINGS
set --ao
ao=alsa
volume=50
volume-max=200
alsa-resample=yes

## PLAYER SETTINGS
alpha=no
background="#f2e2c9"
geometry=20%
video-margin-ratio-left=0.04
video-margin-ratio-right=0.04
video-margin-ratio-top=0.04
video-margin-ratio-bottom=0.04

## CAPTION SETTINGS
sub-color="#edcd7d"
sub-font="CozetteVector"
sub-font-size=40
sub-spacing=0.3
sub-pos=90
alang=nl,jp,jpn,en,eng

## SOFTWARE BEHAVIOR
osd-level=0
osc=no
ontop=yes
no-hidpi-window-scale
no-window-dragging
no-input-default-bindings
term-status-msg="${time-pos} / ${duration}"

## HARDWARE SETTINGS
vo=gpu
hwdec=no
hdr-compute-peak=no
image-display-duration=inf
vo-image-format=png
vf=format=colorlevels=full:colormatrix=auto

## THIRD PARTY
script-opts=ytdl_hook-ytdl_path=/usr/bin/yt-dlp

[extension.mp4]
loop-file=yes

[extension.mkv]
loop-file=yes

[extension.webm]
loop-file=yes

[extension.gifv]
loop-file=yes

[extension.gif]
loop-file=yes

[360p]
ytdl-format=bestvideo[height<=360][vcodec=vp9]+bestaudio/bestvideo[height<=360]+bestaudio/best[height<=360]/best
demuxer-max-bytes=1024KiB
