repository=https://void.webconverger.org/current
repository=https://void.webconverger.org/current/multilib
repository=https://void.webconverger.org/current/multilib/nonfree
repository=https://void.webconverger.org/current/nonfree
