call plug#begin('~/.config/vim/plugged')
Plug 'dense-analysis/ale'
Plug 'rstacruz/vim-closer'
Plug 'mg979/vim-visual-multi'
call plug#end()

set makeprg=gcc\ %
scriptencoding utf-8
set encoding=utf-8
set expandtab
set nocompatible
set noswapfile
set mouse=a
set viminfo+=n/tmp/viminfo
set wrap linebreak nolist
set display=lastline
set incsearch
