--  📝 vim configuration by ~ github.com/irhl
--
--
--         TODO 10-02-2023
--
--  [✓]  move from vim to nvim
--  [✓]  do configuration in lua
--  [✓]  install plugins without a plugin manager
--  [✓]  themes in lua (colorscheme dir)
--  [x]  customize tabline

--  Theme: flowershop-crush
--  ~/.config/nvim/lua/themes/flowershop.lua
--
--  Plugins are stored in:
--  ~/.config/nvim/pack/plugins/start
--
--  Plugin configuration is in:
--  ~/.config/nvim/lua/plugins/
--
--  EDITOR ENLIGHTENMENT
--  nvim-treesitter/nvim-treesitter.git"
--  neovim/nvim-lspconfig"
--
--  EDITOR DISCOVERY
--  folke/which-key.nvim"
--  nvim-lua/plenary.nvim"
--  nvim-telescope/telescope.nvim"

--  EXTRA SYNTAX HIGHLIGHTING
--  lewis6991/gitsigns.nvim"
--  brenoprata10/nvim-highlight-colors"
--  lukas-reineke/indent-blankline.nvim.git"
--
--  RICING
--  echasnovski/mini.starter"
--  echasnovski/mini.statusline"
--
--  THIRD PARTY
--  IogaMaster/neocord
--
--  ABILITIES (vimscript)
--  jiangmiao/auto-pairs.git"
--  mg979/vim-visual-multi"
